#Project info
site_name: Susina Configuration Builder
site_description: "Load and build configuration"
site_url: https://susina.github.io/config-builder

#Repository
repo_name: 'susina/config-builder'
repo_url: 'https://github.com/susina/config-builder'
edit_uri: ''

#Copyright
copyright: 'Susina Configuration Builder is licensed under <a href="https://www.apache.org/licenses/LICENSE-2.0">Apache 2.0 license</a>'

#Configuration
theme:
  name: material
  favicon: assets/hammer-and-wrench.png
  palette:
    primary: red
  features:
    - navigation.tabs
    - navigation.top

#Navigation menu
nav:
  - Home: index.md
  - Documentation:
      - Installation: installation.md
      - Usage: usage.md
      - Reference: 
        - Api: methods.md
        - Parameters reference: parameters.md
      - Complete Example: example.md
  - About:
      - Contributing: contributing.md
      - License: license.md

#Usefulmarkdown extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
