Search.appendIndex(
    [
                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigCache",
            "name": "ConfigCache",
            "summary": "Specialized\u0020class\u0020to\u0020cache\u0020the\u0020built\u0020configuration.",
            "url": "classes/Susina-ConfigBuilder-ConfigCache.html"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigCache\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-ConfigCache.html#method___construct"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigCache\u003A\u003AisFresh\u0028\u0029",
            "name": "isFresh",
            "summary": "Check\u0020if\u0020the\u0020cache\u0020is\u0020fresh.",
            "url": "classes/Susina-ConfigBuilder-ConfigCache.html#method_isFresh"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigCache\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020the\u0020data\u0020into\u0020the\u0020cache.",
            "url": "classes/Susina-ConfigBuilder-ConfigCache.html#method_write"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigCache\u003A\u003A\u0024builderSerial",
            "name": "builderSerial",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-ConfigCache.html#property_builderSerial"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigCache\u003A\u003A\u0024serialFile",
            "name": "serialFile",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-ConfigCache.html#property_serialFile"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder",
            "name": "ConfigurationBuilder",
            "summary": "Class\u0020ConfigurationBuilder.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Static\u0020constructor.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_create"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AaddFile\u0028\u0029",
            "name": "addFile",
            "summary": "Add\u0020one\u0020or\u0020more\u0020file\u0020names\u0020to\u0020the\u0020array\u0020of\u0020configuration\u0020files\u0020to\u0020load.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_addFile"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AsetFiles\u0028\u0029",
            "name": "setFiles",
            "summary": "Set\u0020the\u0020name\u0020of\u0020the\u0020configuration\u0020files\u0020to\u0020load.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_setFiles"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AaddDirectory\u0028\u0029",
            "name": "addDirectory",
            "summary": "Add\u0020one\u0020or\u0020more\u0020directories\u0020where\u0020to\u0020find\u0020the\u0020configuration\u0020files.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_addDirectory"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AsetDirectories\u0028\u0029",
            "name": "setDirectories",
            "summary": "Set\u0020the\u0020name\u0020of\u0020the\u0020directories\u0020where\u0020to\u0020find\u0020the\u0020configuration\u0020files\u0020to\u0020load.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_setDirectories"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AsetDefinition\u0028\u0029",
            "name": "setDefinition",
            "summary": "Set\u0020the\u0020object\u0020to\u0020process\u0020the\u0020configuration\u0020parameters.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_setDefinition"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AsetConfigurationClass\u0028\u0029",
            "name": "setConfigurationClass",
            "summary": "Set\u0020the\u0020full\u0020class\u0020name\u0020of\u0020the\u0020configuration\u0020object\u0020to\u0020instantiate.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_setConfigurationClass"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AsetInitMethod\u0028\u0029",
            "name": "setInitMethod",
            "summary": "Set\u0020the\u0020method\u0020to\u0020use\u0020to\u0020initialize\u0020the\u0020configuration\u0020object.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_setInitMethod"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AsetBeforeParams\u0028\u0029",
            "name": "setBeforeParams",
            "summary": "Set\u0020an\u0020array\u0020of\u0020additional\u0020parameters\u0020to\u0020merge\u0020before\u0020loading\u0020the\u0020configuration\u0020files.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_setBeforeParams"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AsetAfterParams\u0028\u0029",
            "name": "setAfterParams",
            "summary": "Set\u0020an\u0020array\u0020of\u0020additional\u0020parameters\u0020to\u0020merge\u0020after\u0020loading\u0020the\u0020configuration\u0020files.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_setAfterParams"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AsetCacheDirectory\u0028\u0029",
            "name": "setCacheDirectory",
            "summary": "Set\u0020the\u0020cache\u0020directory\u0020or\u0020the\u0020CacheInterface\u0020object",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_setCacheDirectory"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AsetReplaces\u0028\u0029",
            "name": "setReplaces",
            "summary": "Set\u0020an\u0020array\u0020of\u0020parameters\u0020to\u0020replace.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_setReplaces"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003A\u0024keepFirstXmlTag",
            "name": "keepFirstXmlTag",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#property_keepFirstXmlTag"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AgetConfiguration\u0028\u0029",
            "name": "getConfiguration",
            "summary": "Return\u0020a\u0020populated\u0020configuration\u0020object.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_getConfiguration"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AgetConfigurationArray\u0028\u0029",
            "name": "getConfigurationArray",
            "summary": "Return\u0020the\u0020loaded\u0020and\u0020processed\u0020configuration\u0020parameters\u0020as\u0020an\u0020associative\u0020array.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_getConfigurationArray"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003ApopulateContainer\u0028\u0029",
            "name": "populateContainer",
            "summary": "Populate\u0020a\u0020container\u0020object\u0020with\u0020the\u0020configuration\u0020values.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_populateContainer"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AgetDotArray\u0028\u0029",
            "name": "getDotArray",
            "summary": "Transform\u0020an\u0020array\u0020in\u0020dotted\u0020notation.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_getDotArray"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AloadParameters\u0028\u0029",
            "name": "loadParameters",
            "summary": "Load\u0020parameters\u0020from\u0020the\u0020configuration\u0020files.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_loadParameters"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AloadConfiguration\u0028\u0029",
            "name": "loadConfiguration",
            "summary": "Process\u0020and\u0020validate\u0020the\u0020configuration.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_loadConfiguration"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003AloadFromCache\u0028\u0029",
            "name": "loadFromCache",
            "summary": "Load\u0020the\u0020configuration\u0020from\u0020cache.",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#method_loadFromCache"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003ACACHE_FILE",
            "name": "CACHE_FILE",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#constant_CACHE_FILE"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003A\u0024files",
            "name": "files",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#property_files"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003A\u0024directories",
            "name": "directories",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#property_directories"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003A\u0024definition",
            "name": "definition",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#property_definition"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003A\u0024configurationClass",
            "name": "configurationClass",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#property_configurationClass"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003A\u0024initMethod",
            "name": "initMethod",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#property_initMethod"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003A\u0024beforeParams",
            "name": "beforeParams",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#property_beforeParams"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003A\u0024afterParams",
            "name": "afterParams",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#property_afterParams"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003A\u0024replaces",
            "name": "replaces",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#property_replaces"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\ConfigurationBuilder\u003A\u003A\u0024cacheDirectory",
            "name": "cacheDirectory",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-ConfigurationBuilder.html#property_cacheDirectory"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Exception\\ConfigurationBuilderException",
            "name": "ConfigurationBuilderException",
            "summary": "Class\u0020ConfigurationBuilderException.",
            "url": "classes/Susina-ConfigBuilder-Exception-ConfigurationBuilderException.html"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\FileLocator",
            "name": "FileLocator",
            "summary": "Class\u0020to\u0020locate\u0020the\u0020configuration\u0020files\u0020to\u0020load.",
            "url": "classes/Susina-ConfigBuilder-FileLocator.html"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\FileLocator\u003A\u003Alocate\u0028\u0029",
            "name": "locate",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-FileLocator.html#method_locate"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\JsonFileLoader",
            "name": "JsonFileLoader",
            "summary": "JsonFileLoader\u0020loads\u0020configuration\u0020parameters\u0020from\u0020json\u0020file.",
            "url": "classes/Susina-ConfigBuilder-Loader-JsonFileLoader.html"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\JsonFileLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loads\u0020a\u0020Json\u0020file.",
            "url": "classes/Susina-ConfigBuilder-Loader-JsonFileLoader.html#method_load"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\JsonFileLoader\u003A\u003Asupports\u0028\u0029",
            "name": "supports",
            "summary": "Returns\u0020true\u0020if\u0020this\u0020class\u0020supports\u0020the\u0020given\u0020resource.",
            "url": "classes/Susina-ConfigBuilder-Loader-JsonFileLoader.html#method_supports"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\NeonFileLoader",
            "name": "NeonFileLoader",
            "summary": "YamlFileLoader\u0020loads\u0020configuration\u0020parameters\u0020from\u0020yaml\u0020file.",
            "url": "classes/Susina-ConfigBuilder-Loader-NeonFileLoader.html"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\NeonFileLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loads\u0020a\u0020Neon\u0020file.",
            "url": "classes/Susina-ConfigBuilder-Loader-NeonFileLoader.html#method_load"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\NeonFileLoader\u003A\u003Asupports\u0028\u0029",
            "name": "supports",
            "summary": "Returns\u0020true\u0020if\u0020this\u0020class\u0020supports\u0020the\u0020given\u0020resource.",
            "url": "classes/Susina-ConfigBuilder-Loader-NeonFileLoader.html#method_supports"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\PhpFileLoader",
            "name": "PhpFileLoader",
            "summary": "PhpFileLoader\u0020loads\u0020configuration\u0020values\u0020from\u0020a\u0020PHP\u0020file.",
            "url": "classes/Susina-ConfigBuilder-Loader-PhpFileLoader.html"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\PhpFileLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loads\u0020a\u0020PHP\u0020file.",
            "url": "classes/Susina-ConfigBuilder-Loader-PhpFileLoader.html#method_load"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\PhpFileLoader\u003A\u003Asupports\u0028\u0029",
            "name": "supports",
            "summary": "Returns\u0020true\u0020if\u0020this\u0020class\u0020supports\u0020the\u0020given\u0020resource.",
            "url": "classes/Susina-ConfigBuilder-Loader-PhpFileLoader.html#method_supports"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\XmlFileLoader",
            "name": "XmlFileLoader",
            "summary": "XmlFileLoader\u0020loads\u0020configuration\u0020parameters\u0020from\u0020xml\u0020file.",
            "url": "classes/Susina-ConfigBuilder-Loader-XmlFileLoader.html"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\XmlFileLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-Loader-XmlFileLoader.html#method___construct"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\XmlFileLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loads\u0020a\u0020Xml\u0020file.",
            "url": "classes/Susina-ConfigBuilder-Loader-XmlFileLoader.html#method_load"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\XmlFileLoader\u003A\u003Asupports\u0028\u0029",
            "name": "supports",
            "summary": "Returns\u0020true\u0020if\u0020this\u0020class\u0020supports\u0020the\u0020given\u0020resource.",
            "url": "classes/Susina-ConfigBuilder-Loader-XmlFileLoader.html#method_supports"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\XmlFileLoader\u003A\u003A\u0024keepFirstTag",
            "name": "keepFirstTag",
            "summary": "",
            "url": "classes/Susina-ConfigBuilder-Loader-XmlFileLoader.html#property_keepFirstTag"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\YamlFileLoader",
            "name": "YamlFileLoader",
            "summary": "YamlFileLoader\u0020loads\u0020configuration\u0020parameters\u0020from\u0020yaml\u0020file.",
            "url": "classes/Susina-ConfigBuilder-Loader-YamlFileLoader.html"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\YamlFileLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loads\u0020a\u0020Yaml\u0020file.",
            "url": "classes/Susina-ConfigBuilder-Loader-YamlFileLoader.html#method_load"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader\\YamlFileLoader\u003A\u003Asupports\u0028\u0029",
            "name": "supports",
            "summary": "Returns\u0020true\u0020if\u0020this\u0020class\u0020supports\u0020the\u0020given\u0020resource.",
            "url": "classes/Susina-ConfigBuilder-Loader-YamlFileLoader.html#method_supports"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder",
            "name": "ConfigBuilder",
            "summary": "",
            "url": "namespaces/susina-configbuilder.html"
        },                {
            "fqsen": "\\Susina",
            "name": "Susina",
            "summary": "",
            "url": "namespaces/susina.html"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/susina-configbuilder-exception.html"
        },                {
            "fqsen": "\\Susina\\ConfigBuilder\\Loader",
            "name": "Loader",
            "summary": "",
            "url": "namespaces/susina-configbuilder-loader.html"
        }            ]
);
