name: Build and deploy documentation
on:
  release:
    types: [published]
jobs:
  build_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Install dependencies
        run: python -m pip install --upgrade pip mkdocs mkdocs-material
      - name: Build the documentation site
        run: mkdocs build
      - name: Deploy documentation to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

  build_api:
    needs: build_documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none
      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--prefer-dist --optimize-autoloader"
      - name: Download phpDocumentor phar archive
        run: wget https://phpdoc.org/phpDocumentor.phar
      - name: Build the coumentation api
        run: php phpDocumentor.phar
      - name: Deploy documentation api to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site/api
          destination_dir: api

