# Run test suite
name: Tests
on: [push, pull_request]
jobs:
  install_tools:
    name: Install tools
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Install tools
        uses: ngmy/phive-install-action@master
      - name: Upload tools to artifact store
        uses: actions/upload-artifact@v7
        with:
          name: tools
          path: tools
  test:
    name: Test suite
    needs: install_tools
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest", "macOs-latest", "windows-latest"]
        php-versions: ["8.5"]
        symfony-version: ["7.4", "8.1"]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Set autocrlf on windows
        if: matrix.operating-system == 'windows-latest'
        run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: libxml, simplexml, dom
          coverage: none
      - name: Move specific composer.json (Symfony version ${{ matrix.symfony-version }})
        run: |
          rm composer.json
          mv resources/composer/composer-symfony${{ matrix.symfony-version }}.json composer.json
      - name: Install composer dependencies
        uses: ramsey/composer-install@v4
        with:
          composer-options: "--prefer-dist --optimize-autoloader"
      - name: Download tools from artifact store
        uses: actions/download-artifact@v7
        with:
          name: tools
          path: tools
      - name: Check coding standard
        run: composer cs:check
      - name: Static analysis tool
        run: composer analytics
      - name: Test suite
        run: composer test
